name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    outputs:
      should_build: ${{ steps.detect.outputs.should_build }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      workflow: write
    steps:
      - name: Checkout rolling source
        uses: actions/checkout@v4
        with:
          ref: patch
          depth: 0
      - name: Sync rolling and detect docker changes
        id: detect
        shell: bash
        run: |
          bash .github/workflows/script/sync-and-detect-docker-changes.sh \
            "$REPOSITORY" \
            "$BRANCH_NAME" \
            "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: rolling

  build:
    needs: sync
    if: needs.sync.outputs.should_build == 'true'
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
